version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: db_maderas_mendi
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

networks:
  default:
    driver: bridge
